//person related actions
export const ADD_CONTACT = "ADD_PERSON";
export const SORT_CONTACT_LIST = "SORT_CONTACT_LIST";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const TOGGLE_CONTACT_OPTION_PANE = "TOGGLE_CONTACT_OPTION_PANE";
export const TOGGLE_CONTACT_EDIT_FORM = "TOGGLE_CONTACT_EDIT_FORM";
export const REFRESH_CONTACT_LIST = "REFRESH_CONTACT_LIST";
